// <auto-generated />
namespace PostMeService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Model3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model3));
        
        string IMigrationMetadata.Id
        {
            get { return "201903161530308_Model3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
